[versions]
ktor = "3.3.0"

[libraries]
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-server-netty = { group = "io.ktor", name = "ktor-server-netty", version.ref = "ktor" }

envconf = { group = "dev.schlaubi", name = "stdx-envconf", version = "1.3.0" }

slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version = "2.0.16" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.2.20" }
